
DO $$
BEGIN
   IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'oa_reader') THEN
      CREATE ROLE oa_reader LOGIN PASSWORD 'oa_reader_readonly_782997781';
   END IF;
END
$$;

GRANT CONNECT ON DATABASE security_oa TO oa_reader;
GRANT USAGE ON SCHEMA public TO oa_reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO oa_reader;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO oa_reader;

ALTER DEFAULT PRIVILEGES FOR ROLE oa_user IN SCHEMA public GRANT SELECT ON TABLES TO oa_reader;
ALTER DEFAULT PRIVILEGES FOR ROLE oa_user IN SCHEMA public GRANT SELECT ON SEQUENCES TO oa_reader;
