#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Step 2: 上传并执行 seed PHP 脚本"""
import paramiko

ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('172.20.0.139', username='nbcy', password='admin123', timeout=10)

PHP = r"""<?php
require_once __DIR__ . '/vendor/autoload.php';
$app = require_once __DIR__ . '/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);
$kernel->bootstrap();
echo "=== START ===\n";
use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Hash;
use App\Models\User; use App\Models\Department; use App\Models\Position;
use App\Models\EmployeeProfile; use App\Models\SkillTag; use App\Models\Certificate;
use App\Models\Customer; use App\Models\CustomerContact; use App\Models\CustomerDevice; use App\Models\FollowUpRecord;
use App\Models\Project; use App\Models\ProjectContract; use App\Models\Supplier; use App\Models\ConstructionLog;
use App\Models\ServiceOrder; use App\Models\ServiceOrderLog; use App\Models\MaintenanceContract;
use App\Models\ExpenseClaim; use App\Models\ExpenseItem;
use App\Models\Vehicle; use App\Models\VehicleInsurance; use App\Models\VehicleMaintenanceRecord; use App\Models\VehicleUsageRequest;
use App\Models\Warehouse; use App\Models\InventoryItem; use App\Models\StockRecord;
use App\Models\Receivable; use App\Models\Payable;
use App\Models\DiskFolder; use App\Models\DiskFile;
use App\Models\KnowledgeCategory; use App\Models\KnowledgeArticle;
use App\Models\AttendanceRecord; use App\Models\LeaveRequest; use App\Models\OvertimeRequest;
$ok=0;$er=0;
function S($n,$fn){global $ok,$er;try{$c=$fn();$ok++;echo "  OK $n: $c\n";}catch(\Exception $e){$er++;echo "  ERR $n: ".$e->getMessage()."\n";}}

echo "--1 Dept/Pos--\n";
S('部门',function(){$d=[['总经理办公室',null,1],['工程部',null,2],['技术支持部',null,3],['销售部',null,4],['财务部',null,5],['行政人事部',null,6],['采购部',null,7],['施工一队',2,1],['施工二队',2,2],['维保组',3,3]];foreach($d as $v)Department::create(['name'=>$v[0],'parent_id'=>$v[1],'manager_id'=>$v[2],'sort_order'=>$v[2],'status'=>'active']);return count($d);});
S('岗位',function(){$dm=Department::pluck('id','name')->toArray();$ps=['总经理办公室'=>[['总经理',1],['副总经理',2]],'工程部'=>[['工程经理',1],['项目经理',2],['施工主管',3],['弱电工程师',4]],'技术支持部'=>[['技术经理',1],['技术主管',2],['维保工程师',3]],'销售部'=>[['销售经理',1],['销售主管',2],['业务员',3]],'财务部'=>[['财务经理',1],['会计',2],['出纳',3]],'行政人事部'=>[['行政经理',1],['人事专员',2]],'采购部'=>[['采购经理',1],['采购专员',2]],'施工一队'=>[['队长',1],['组员',3]],'施工二队'=>[['队长',1],['组员',3]],'维保组'=>[['组长',1],['组员',2]];$c=0;foreach($ps as $dn=>$pl){$did=$dm[$dn]??1;foreach($pl as $p){Position::create(['name'=>$p[0],'department_id'=>$did,'level'=>$p[1],'status'=>'active','sort_order'=>$p[1]]);$c++;}}return $c;});

echo "--2 Emp--\n";
S('用户+档案',function(){$nms=['王强','李伟','张敏','赵磊','刘洋','陈静','杨帆','黄海','周婷','吴刚','孙亮','马超','朱丽','胡明','郭峰','林芳','何军','高洁','罗勇','梁志远'];$ds=Department::pluck('id')->toArray();$c=0;foreach($nms as $i=>$nm){$did=$ds[($i+1)%count($ds)];$u=User::create(['name'=>$nm,'username'=>'user'.($i+6),'email'=>'u'.($i+6).'@oa.com','phone'=>'138'.str_pad(rand(10000000,99999999),8,'0'),'password'=>Hash::make('admin123'),'department_id'=>$did,'status'=>'active','gender'=>($i%3==0)?'female':'male']);EmployeeProfile::create(['user_id'=>$u->id,'employee_no'=>'EMP'.str_pad($i+6,4,'0',STR_PAD_LEFT),'hire_date'=>now()->subDays(rand(30,730))->toDateString(),'contract_type'=>['fixed','open','trial'][rand(0,2)],'contract_start'=>now()->subDays(rand(30,365))->toDateString(),'contract_end'=>now()->addDays(rand(180,730))->toDateString(),'base_salary'=>rand(5000,2000)*10+5000,'salary_allowance'=>rand(500,3000),'emergency_contact'=>'联系人','emergency_phone'=>'139'.str_pad(rand(10000000,99999999),8,'0')]);$c++;}return $c;});
S('技能+证书',function(){$cats=['install','debug','network','maintain','other'];foreach(['海康安装','大华调试','监控','门禁','报警','布线','弱电','CAD','电气','网络'] as $s)SkillTag::create(['name'=>$s,'category'=>$cats[array_rand($cats)],'color'=>'#409eff']);$eps=EmployeeProfile::all();$sids=SkillTag::pluck('id')->toArray();$c=0;foreach($eps as $ep){$n=rand(2,4);$sel=array_rand($sids,min($n,count($sids)));if(!is_array($sel))$sel=[$sel];foreach($sel as $sid){DB::table('employee_skills')->insertOrIgnore(['employee_profile_id'=>$ep->id,'skill_tag_id'=>$sids[$sid],'proficiency'=>rand(1,5),'created_at'=>now(),'updated_at'=>now()]);$c++;}}foreach($eps as $ep){if(rand(0,1))continue;Certificate::create(['employee_profile_id'=>$ep->id,'certificate_name'=>['电工证','弱电证','消防证','建造师'][rand(0,3)],'certificate_no'=>'C'.rand(100000,999999),'issue_date'=>now()->subYears(rand(1,5))->toDateString(),'expire_date'=>now()->addDays(rand(-30,730))->toDateString(),'issuer'=>'培训机构','status'=>'valid','remind_days'=>30]);$c++;}return $c;});

echo "--3 Cust--\n";
S('客户',function(){$cs=[['瑞丰科技产业园','科技','vip'],['万达商业广场','地产','vip'],['恒大地产集团','房地产','vip'],['鹏程实验学校','教育','normal'],['阳光医院','医疗','normal'],['锦绣花园小区','物业','normal'],['鼎盛制造有限公司','制造','normal'],['中鼎国际酒店','酒店','vip'],['绿城物业','物业','normal'],['天安数码城','产业园','normal'],['国盛证券大厦','金融','vip'],['红星美凯龙','零售','normal'],['博瑞生物','医药','normal'],['锦绣幼儿园','教育','normal'],['通泰物流','物流','normal']];$us=User::where('id','>',5)->pluck('id')->toArray();$dt=['camera','access_control','alarm','network','fire','other'];$ds=['normal','fault','maintaining'];$c=0;foreach($cs as $c0){$cu=Customer::create(['name'=>$c0[0],'credit_code'=>'91'.rand(100000,999999).'AB','industry'=>$c0[1],'category'=>$c0[2],'province'=>'北京市','city'=>'北京市','district'=>$c0[0],'address'=>$c0[0],'tags'=>['安防'],'source'=>['网络','转介绍','展会'][rand(0,2)],'status'=>'active','assigned_user_id'=>$us[array_rand($us)]]);$c++;CustomerContact::create(['customer_id'=>$cu->id,'name'=>'张经理','position'=>'工程部','phone'=>'139'.rand(10000000,99999999),'is_primary'=>true]);CustomerContact::create(['customer_id'=>$cu->id,'name'=>'李总','position'=>'管理层','phone'=>'138'.rand(10000000,99999999),'is_primary'=>false]);for($d=0;$d<rand(2,5);$d++)CustomerDevice::create(['customer_id'=>$cu->id,'device_name'=>['摄像头','NVR','门禁控制器','报警主机','对讲机'][$d%5],'device_type'=>$dt[$d%6],'brand'=>'海康','model'=>'DS-'.$d,'serial_number'=>'SN'.rand(100000,999999),'install_location'=>'现场','install_date'=>now()->subDays(rand(30,730))->toDateString(),'warranty_end'=>now()->addDays(rand(-30,730))->toDateString(),'status'=>$ds[rand(0,2)]]);}return $c;});
S('跟进',function(){$cs=Customer::all();$us=User::where('id','>',5)->pluck('id')->toArray();$ts=['visit','call','online','other'];$c=0;foreach($cs as $cu){for($i=0;$i<rand(2,5);$i++){FollowUpRecord::create(['customer_id'=>$cu->id,'user_id'=>$us[array_rand($us)],'type'=>$ts[array_rand($ts)],'content'=>'沟通安防需求','next_follow_up_date'=>now()->addDays(rand(3,14))->toDateString(),'next_follow_up_note'=>'跟进方案']);$c++;}}return $c;});

echo "--4 Proj--\n";
S('项目+供应商',function(){$cs=Customer::inRandomOrder()->limit(12)->get();$us=User::where('id','>',2)->pluck('id')->toArray();$stg=['initiation','inquiry','contract','purchase','construction','settlement','warranty'];$tp=['camera','access_control','alarm','comprehensive','network','cloud_platform'];$nms=['视频监控改造','门禁系统安装','报警系统升级','综合安防平台','停车场管理','对讲系统','周界防范','智能楼宇','消防联动','巡更系统','监控扩容','人脸门禁'];$pr=['low','medium','high','urgent'];$c=0;foreach($cs as $i=>$cu){$st=$stg[array_rand($stg)];$bd=rand(5,200)*10000;$sd=now()->subDays(rand(10,365));$ed=(clone $sd)->addDays(rand(30,180));$p=Project::create(['project_no'=>'PRJ2025'.str_pad($c+1,3,'0',STR_PAD_LEFT),'name'=>$cu->name.'-'.$nms[$c%12],'customer_id'=>$cu->id,'type'=>$tp[$c%6],'stage'=>$st,'status'=>in_array($st,['settlement','warranty'])?'completed':'in_progress','budget_device'=>$bd*0.5,'budget_material'=>$bd*0.15,'budget_labor'=>$bd*0.25,'budget_outsource'=>$bd*0.05,'budget_other'=>$bd*0.05,'progress'=>in_array($st,['warranty'])?100:rand(10,95),'manager_id'=>$us[array_rand($us)],'start_date'=>$sd->toDateString(),'end_date'=>$ed->toDateString(),'actual_end_date'=>in_array($st,['warranty','settlement'])?$ed->toDateString():null,'priority'=>$pr[rand(0,3)]]);ProjectContract::create(['project_id'=>$p->id,'contract_no'=>'HT'.date('Ymd').rand(100,999),'contract_amount'=>$bd,'payment_method'=>'installment','contract_start'=>$sd->toDateString(),'contract_end'=>$ed->toDateString(),'status'=>'active','signed_at'=>$sd]);for($j=0;$j<rand(3,6);$j++)ConstructionLog::create(['project_id'=>$p->id,'user_id'=>$us[array_rand($us)],'work_date'=>$sd->copy()->addDays($j+1)->toDateString(),'weather'=>['晴','多云','阴'][rand(0,2)],'content'=>'完成安装'.($j+1),'work_hours'=>rand(60,100)/10.0]);$c++;}foreach([['海康代理商','张经理','0571-8001'],['大华代理商','李经理','0571-8002'],['线缆供应商','刘经理','021-8003'],['辅材供应商','陈经理','0571-8004'],['UPS供应商','杨经理','020-8005']] as $s)Supplier::create(['name'=>$s[0],'contact_person'=>$s[1],'phone'=>$s[2],'category'=>['设备','辅材'][rand(0,1)],'rating'=>rand(3,5),'status'=>'active']);return $c;});

echo "--5 Svc--\n";
S('售后工单',function(){$cs=Customer::inRandomOrder()->limit(10)->get();$us=User::where('id','>',2)->pluck('id')->toArray();$sts=['pending','assigned','in_progress','completed','confirmed','archived','cancelled'];$ugs=['normal','urgent','critical'];$fts=['画面模糊','无法刷卡','回放失败','误报','离线','存储满','控制器故障','无声音','道闸不开','识别失败','卡顿','断网'];$sv=['warranty','non_warranty','maintenance'];$c=0;foreach($cs as $cu){for($i=0;$i<rand(2,5);$i++){$st=$sts[array_rand($sts)];$so=ServiceOrder::create(['order_no'=>'SO2025'.str_pad(rand(1,999),3,'0',STR_PAD_LEFT),'customer_id'=>$cu->id,'fault_description'=>$fts[array_rand($fts)],'urgency'=>$ugs[array_rand($ugs)],'service_type'=>$sv[array_rand($sv)],'status'=>$st,'assigned_to'=>$us[array_rand($us)],'assigned_at'=>in_array($st,['assigned','in_progress','completed','confirmed'])?now():null,'started_at'=>in_array($st,['in_progress','completed','confirmed'])?now()->subHours(rand(1,48)):null,'completed_at'=>in_array($st,['completed','confirmed'])?now()->subHours(rand(1,24)):null,'created_by'=>$us[array_rand($us)],'sla_hours'=>[4,8,24,48][rand(0,3)]]);if(!in_array($st,['pending','cancelled']))ServiceOrderLog::create(['service_order_id'=>$so->id,'user_id'=>$us[array_rand($us)],'action'=>'assigned','content'=>'已派发']);if(in_array($st,['in_progress','completed','confirmed']))ServiceOrderLog::create(['service_order_id'=>$so->id,'user_id'=>$us[array_rand($us)],'action'=>'started','content'=>'到达现场']);$c++;}}foreach($cs->take(5) as $cu)MaintenanceContract::create(['contract_no'=>'WB'.date('Ymd').rand(100,999),'customer_id'=>$cu->id,'amount'=>rand(1,10)*10000,'start_date'=>now()->subMonths(rand(1,12))->toDateString(),'end_date'=>now()->addMonths(rand(1,12))->toDateString(),'inspection_frequency'=>['monthly','quarterly','biannual'][rand(0,2)],'scope'=>'安防维保','status'=>'active']);return $c;});

echo "--6 Exp--\n";
S('报销',function(){$us=User::where('id','>',5)->pluck('id')->toArray();$cats=['travel','hospitality','office','transport','project_cost','other'];$descs=['住宿费','招待费','办公费','交通费','材料费','其他'];$sts=['draft','submitted','approved','rejected','paid'];$c=0;foreach($us as $uid){for($i=0;$i<rand(1,4);$i++){$ci=array_rand($cats);$a=rand(100,5000);$st=$sts[array_rand($sts)];$cl=ExpenseClaim::create(['user_id'=>$uid,'category'=>$cats[$ci],'total_amount'=>$a,'description'=>$descs[$ci],'status'=>$st,'approver_id'=>1,'approved_at'=>in_array($st,['approved','paid'])?now():null,'paid_amount'=>$st=='paid'?$a:0,'paid_at'=>$st=='paid'?now():null]);for($j=0;$j<rand(1,3);$j++)ExpenseItem::create(['expense_claim_id'=>$cl->id,'item_date'=>now()->subDays(rand(1,30))->toDateString(),'description'=>$descs[$ci],'amount'=>round($a/rand(1,3),2),'category'=>$cats[$ci]]);$c++;}}return $c;});

echo "--7 Veh--\n";
S('车辆',function(){$us=User::pluck('id')->toArray();$ds=Department::pluck('id')->toArray();$fu=['gas','diesel','electric','hybrid'];$vs=['normal','maintenance'];$vids=[];foreach([['皖A12345','五菱','宏光',58000],['皖B56789','江淮','瑞风',125000],['皖C90123','丰田','卡罗拉',148000],['皖D34567','金杯','海狮',89000],['皖E78901','比亚迪','宋PLUS',156000]] as $v){$ve=Vehicle::create(['plate_no'=>$v[0],'brand'=>$v[1],'model'=>$v[2],'color'=>'白色','purchase_date'=>now()->subDays(rand(365,1095))->toDateString(),'purchase_price'=>$v[3],'department_id'=>$ds[array_rand($ds)],'responsible_user_id'=>$us[array_rand($us)],'status'=>$vs[rand(0,1)],'vin'=>'LSVAU'.rand(100000,999999),'engine_no'=>'E'.rand(100000,999999),'seats'=>rand(5,9),'fuel_type'=>$fu[rand(0,3)]]);$vids[]=$ve->id;VehicleInsurance::create(['vehicle_id'=>$ve->id,'insurance_company'=>'中国人保','policy_no'=>'PICC'.rand(100000,999999),'type'=>'交强险','premium'=>rand(2000,6000),'start_date'=>now()->toDateString(),'end_date'=>now()->addYear()->toDateString(),'status'=>'active']);VehicleMaintenanceRecord::create(['vehicle_id'=>$ve->id,'maintenance_type'=>'保养','mileage'=>rand(5000,30000),'cost'=>rand(300,2000),'maintenance_date'=>now()->subDays(rand(10,180))->toDateString(),'description'=>'更换机油','handled_by'=>$us[array_rand($us)]]);}foreach($vids as $vid){for($i=0;$i<rand(3,8);$i++){VehicleUsageRequest::create(['vehicle_id'=>$vid,'applicant_id'=>$us[array_rand($us)],'usage_date'=>now()->subDays(rand(1,30))->toDateString(),'start_time'=>'08:00','end_time'=>'18:00','destination'=>['现场','公司','仓库','工地'][rand(0,3)],'purpose'=>'施工用车','passengers'=>rand(1,5),'self_drive'=>rand(0,1)?true:false,'status'=>['draft','submitted','approved','rejected'][rand(0,3)],'approver_id'=>1,'approved_at'=>now(),'actual_mileage'=>rand(20,200)]);}}return count($vids);});

echo "--8 Inv--\n";
S('库存',function(){$us=User::pluck('id')->toArray();Warehouse::create(['name'=>'主仓库','code'=>'WH01','type'=>'main','address'=>'一楼','manager_id'=>$us[0],'status'=>'active']);Warehouse::create(['name'=>'辅材仓库','code'=>'WH02','type'=>'aftermarket','address'=>'二楼','manager_id'=>$us[1],'status'=>'active']);$wId=Warehouse::first()->id;$items=[['海康摄像头','DS-2CD2T47G2','install',850,'台'],['NVR录像机','DS-7608N','debug',3200,'台'],['门禁控制器','ASI7213','install',1500,'台'],['读卡器','DAIC-MF','debug',280,'个'],['报警主机','2316','maintain',2100,'台'],['红外探测器','PB-60','install',450,'对'],['网线CAT6','CAT6','network',380,'箱'],['电源线','RVV','other',180,'卷'],['PVC管','PVC25','install',12,'根'],['水晶头','RJ45','network',35,'盒'],['支架','不锈钢','install',25,'个'],['光纤跳线','SC-LC','network',15,'条'],['收发器','百兆','network',120,'对'],['交换机','16口','network',680,'台'],['UPS','1KVA','other',1500,'台'],['硬盘','4TB','other',520,'块']];$srT=['in','out','transfer','check'];$c=0;foreach($items as $it){$st=rand(5,100);InventoryItem::create(['name'=>$it[0],'code'=>'ITM'.str_pad($c+1,4,'0',STR_PAD_LEFT),'category'=>$it[2],'specification'=>$it[1],'unit'=>$it[3],'safety_stock'=>10,'current_stock'=>$st,'cost_price'=>floatval($it[4]),'sell_price'=>round(floatval($it[4])*1.3,2),'warehouse_id'=>$wId,'location'=>'A'.rand(1,5).'-'.rand(1,10),'has_serial'=>in_array($it[2],['install','debug','maintain']),'status'=>$st<=10?'low_stock':'normal']);for($j=0;$j<rand(1,4);$j++)StockRecord::create(['record_no'=>'SR'.date('Ymd').str_pad($c+1,3,'0',STR_PAD_LEFT),'inventory_item_id'=>$c+1,'warehouse_id'=>$wId,'type'=>$srT[array_rand($srT)],'quantity'=>rand(1,10),'remaining_stock'=>$st,'operator_id'=>$us[array_rand($us)]]);$c++;}return $c;});

echo "--9 Fin--\n";
S('财务',function(){$cs=Customer::inRandomOrder()->limit(8)->get();$ss=Supplier::inRandomOrder()->limit(4)->get();$pId=Project::first()?Project::first()->id:null;$c=0;foreach($cs as $cu){$a=rand(5,100)*10000;$r=rand(0,round($a*0.8/10000))*10000;Receivable::create(['customer_id'=>$cu->id,'project_id'=>$pId,'amount'=>$a,'received_amount'=>$r,'remaining_amount'=>$a-$r,'due_date'=>now()->addDays(rand(-30,90))->toDateString(),'received_date'=>$r>0?now()->subDays(rand(1,30))->toDateString():null,'status'=>($a-$r)<=0?'paid':'partial']);$c++;}foreach($ss as $su){$a=rand(2,50)*10000;$p=rand(0,round($a*0.7/10000))*10000;Payable::create(['supplier_id'=>$su->id,'project_id'=>$pId,'amount'=>$a,'paid_amount'=>$p,'remaining_amount'=>$a-$p,'due_date'=>now()->addDays(rand(-15,60))->toDateString(),'paid_date'=>$p>0?now()->subDays(rand(1,30))->toDateString():null,'payment_term'=>'月结30天','status'=>($a-$p)<=0?'paid':'partial']);$c++;}return $c;});

echo "--10 Att--\n";
S('考勤',function(){$us=User::where('status','active')->where('id','>',5)->get();$lts=['annual','personal','sick','marriage','other'];$ac=0;$lc=0;$oc=0;for($d=29;$d>=0;$d--){$dt=now()->subDays($d);if($dt->isWeekend())continue;foreach($us as $u){if(rand(1,100)>85)continue;AttendanceRecord::create(['user_id'=>$u->id,'date'=>$dt->toDateString(),'clock_in'=>$dt->copy()->setTime(8,rand(0,30))->toDateTimeString(),'clock_in_location'=>'公司','clock_out'=>$dt->copy()->setTime(17,rand(30,59))->toDateTimeString(),'clock_out_location'=>'公司','status'=>'normal','work_hours'=>8.0,'overtime_hours'=>rand(0,30)/10.0]);$ac++;}}foreach($us as $u){if(rand(0,1))continue;for($j=0;$j<rand(1,2);$j++)LeaveRequest::create(['user_id'=>$u->id,'type'=>$lts[array_rand($lts)],'start_date'=>now()->subDays(rand(1,15))->toDateString(),'end_date'=>now()->subDays(rand(0,14))->toDateString(),'days'=>rand(1,5).'.0','reason'=>'个人事务','status'=>['pending','approved','rejected'][rand(0,2)],'approver_id'=>1]);$lc++;}foreach($us->take(10) as $u){if(rand(0,1))continue;OvertimeRequest::create(['user_id'=>$u->id,'overtime_date'=>now()->subDays(rand(1,14))->toDateString(),'start_time'=>'18:00','end_time'=>['20:00','21:00','22:00'][rand(0,2)],'hours'=>[2.0,3.0,4.0][rand(0,2)],'reason'=>'项目加班','compensation_type'=>['pay','leave'][rand(0,1)],'status'=>['pending','approved'][rand(0,1)],'approver_id'=>1]);$oc++;}return "$ac/$lc/$oc";});

echo "--11 Disk--\n";
S('网盘',function(){$us=User::pluck('id')->toArray();$c=0;foreach(['公司制度','项目资料','技术文档','培训资料','安全管理'] as $nm){DiskFolder::create(['name'=>$nm,'path'=>'/'.$nm,'created_by'=>$us[array_rand($us)],'is_system'=>false]);$c++;}$fids=DiskFolder::pluck('id')->toArray();foreach([['安防设计规范.pdf',0,2e6],['施工标准.pdf',0,1.5e6],['海康安装手册.pdf',2,5e5],['大华配置指南.pdf',2,7.5e5],['项目总结.xlsx',1,2.5e5],['验收模板.docx',1,1.3e5],['考勤制度.pdf',0,2.5e5],['NVR计算表.xlsx',2,6e4]] as $f){DiskFile::create(['folder_id'=>$fids[$f[1]]??$fids[0],'name'=>$f[0],'original_name'=>$f[0],'extension'=>substr(strrchr($f[0],'.'),1),'mime_type'=>'application/octet-stream','size'=>$f[2],'path'=>'/storage/'.$f[0],'uploaded_by'=>$us[array_rand($us)],'version'=>1,'is_starred'=>rand(0,1)]);$c++;}return $c;});

echo "--12 KB--\n";
S('知识库',function(){$us=User::pluck('id')->toArray();$c=0;$cd=[['安防基础',null],['设备安装',null],['故障排查',null],['项目管理',null],['行业标准',null],['视频监控','安防基础'],['门禁系统','安防基础'],['报警系统','安防基础'],['安装规范','设备安装'],['故障诊断','故障排查'],['弱电规范','行业标准']];$cm=[];foreach($cd as $v){$par=($v[1]!==null&&isset($cm[$v[1]]))?$cm[$v[1]]:null;$cat=KnowledgeCategory::create(['parent_id'=>$par,'name'=>$v[0],'icon'=>'document','sort_order'=>$c]);$cm[$v[0]]=$cat->id;$c++;}foreach([['摄像机选型','视频监控','介绍摄像机选型方法'],['存储计算','视频监控','NVR容量计算'],['布线规范','门禁系统','布线技术要求'],['报警调试','报警系统','报警主机配置'],['安装角度','安装规范','安装高度角度'],['平台配置','故障诊断','iVMS问题解决'],['验收标准','弱电规范','验收标准'],['成本控制','项目管理','成本管控方法'],['进度管理','项目管理','施工工期控制'],['国标解读','行业标准','GB50198解读']] as $a){KnowledgeArticle::create(['category_id'=>$cm[$a[1]]??1,'title'=>$a[0],'content'=>'<h2>'.$a[0].'</h2><p>'.$a[2].'</p><p>详细内容。</p>','author_id'=>$us[array_rand($us)],'tags'=>['安防','技术'],'view_count'=>rand(10,500),'like_count'=>rand(0,50),'status'=>'published','published_at'=>now()->subDays(rand(1,180)),'summary'=>$a[2]]);$c++;}return $c;});

echo "--13 Log--\n";
S('日志',function(){$us=User::pluck('id')->toArray();$c=0;$ts=['login','logout','operation','login_failed'];for($d=29;$d>=0;$d--){for($j=0;$j<rand(3,10);$j++){DB::table('system_logs')->insert(['user_id'=>$us[array_rand($us)],'type'=>$ts[array_rand($ts)],'module'=>['auth','project','service','expense','dashboard'][rand(0,4)],'action'=>['login','view','create','update'][rand(0,3)],'description'=>'操作记录','ip'=>'192.168.1.'.rand(1,254),'user_agent'=>'Mozilla/5.0','created_at'=>now()->subDays($d)->subHours(rand(8,18))]);$c++;}}return $c;});

echo "\n=== DONE: $ok OK, $er ERR ===\n";
"""

# Chown, upload via SFTP, then execute via SSH
stdin, stdout, stderr = ssh.exec_command('echo admin123 | sudo -S chown nbcy:nbcy /var/www/oa-api', timeout=10)
stdout.read()

sftp = ssh.open_sftp()
with sftp.open('/var/www/oa-api/seed_demo_data.php', 'w') as f:
    f.write(PHP)
sftp.close()

print("Executing seed PHP...")
stdin, stdout, stderr = ssh.exec_command('echo admin123 | sudo -S bash -c "cd /var/www/oa-api && php seed_demo_data.php 2>&1"', timeout=120)
out = stdout.read().decode('utf-8', errors='replace')
err = stderr.read().decode('utf-8', errors='replace')
print(out)
if err:
    print(f"STDERR: {err[:500]}")

# Restore permissions
stdin, stdout, stderr = ssh.exec_command('echo admin123 | sudo -S chown www-data:www-data /var/www/oa-api', timeout=10)
stdout.read()

ssh.close()
print("Done!")
