import paramiko
ssh = paramiko.SSHClient()
ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
ssh.connect('172.20.0.139', port=22, username='nbcy', password='admin123')
si,so,se = ssh.exec_command('cat /etc/nginx/sites-enabled/oa-web.conf')
print(so.read().decode())
si,so,se = ssh.exec_command('curl -sS -o /dev/null -w "status:%{http_code} time:%{time_total}s size:%{size_download}B\\n" http://127.0.0.1:3000/')
print(so.read().decode())
si,so,se = ssh.exec_command('curl -sS http://127.0.0.1:3000/ | head -c 400')
print(so.read().decode())
ssh.close()
