
DELETE FROM model_has_roles WHERE model_type = 'App\Models\User' AND model_id >= 74;
INSERT INTO model_has_roles (role_id, model_type, model_id) VALUES
  (1, 'App\Models\User', 74),
  (2, 'App\Models\User', 75),
  (2, 'App\Models\User', 76),
  (2, 'App\Models\User', 77),
  (2, 'App\Models\User', 78),
  (3, 'App\Models\User', 79),
  (3, 'App\Models\User', 80),
  (4, 'App\Models\User', 81),
  (4, 'App\Models\User', 82),
  (4, 'App\Models\User', 83),
  (4, 'App\Models\User', 84),
  (4, 'App\Models\User', 85),
  (4, 'App\Models\User', 86),
  (4, 'App\Models\User', 87),
  (4, 'App\Models\User', 88),
  (1, 'App\Models\User', 89),
  (2, 'App\Models\User', 90),
  (2, 'App\Models\User', 91),
  (2, 'App\Models\User', 92),
  (2, 'App\Models\User', 93),
  (3, 'App\Models\User', 94),
  (3, 'App\Models\User', 95),
  (4, 'App\Models\User', 96),
  (4, 'App\Models\User', 97),
  (4, 'App\Models\User', 98),
  (4, 'App\Models\User', 99),
  (4, 'App\Models\User', 100),
  (4, 'App\Models\User', 101),
  (4, 'App\Models\User', 102),
  (4, 'App\Models\User', 103);
